prod:
  hosts:
    client1:
       ansible_host: 192.168.99.11 # A remplacer par l'IP de votre client
dev:
  hosts:         
    client2:
       ansible_host: 192.168.99.12 # A remplacer par l'IP de votre client
